# render.yaml
# Blueprint for deploying on Render's FREE TIER.
# WARNING: This setup uses an ephemeral filesystem. All data (database,
# uploaded files, logs) will be DELETED on every restart or deploy.

services:
  #--------------------------------
  # Service 1: The Flask Web Panel (Free Instance)
  #--------------------------------
  - type: web
    name: gakuma-panel-free
    env: python
    # This sets the service to use the free instance type.
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # Render's free web services use port 10000
    startCommand: "gunicorn app:app --bind 0.0.0.0:10000 --threads 4"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6

  #---------------------------------
  # Service 2: The Telegram Bot (Free Instance)
  #---------------------------------
  - type: worker
    name: gakuma-bot-free
    env: python
    # This sets the service to use the free instance type.
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      # This allows the bot to communicate with the web panel over Render's private network.
      # The name and port must match the web service above.
      - key: PANEL_API_URL
        value: http://gakuma-panel-free:10000
